import "./globals.css";
import Footer from "@/app/components/Footer";
import WhatsAppButton from "@/app/common/WhatsAppButton";

export const metadata = {
  title: "Maazster Edu",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
    apple: "/favicon.ico",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className="font-sans antialiased bg-primary-950 text-primary-100 min-h-screen flex flex-col relative"
      >
        {children}
        <WhatsAppButton />
        <Footer />
      </body>
    </html>
  );
}
